# SprintLog Boot의 기본 설정 파일
# Spring Boot가 초기화 될 때 항상 이 파일을 읽는다.

spring:
  application:
    name: sprintlog-boot

  datasource:
    url: jdbc:postgresql://localhost:5432/sprintlog
    username: sprintlog
    password: sprintlog
    driver-class-name: org.postgresql.Driver
    #내 컴퓨터(localhost)의
    #5432 포트에 실행 중인 PostgreSQL 서버로 가서
    #sprintlog 데이터베이스에
    #sprintlog 계정으로 로그인해라

  jpa:
    hibernate:
      ddl-auto: create  #엔티티 클래스를 보고 CREATE, ALTER를 자동으로 만들어서 DB에 적용
#    show-sql: true #실행되는 SQL을 콘솔에 보여준다
#    properties:
#      hibernate:
#        format_sql: true  #SQL을 보기 좋게 들여쓰기


  profiles:
    active: dev

  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 20MB

server:
  port: 8080

management:
  endpoints:
    web:
      exposure:
        include: health, info, metrics # 꼭 필요한 정보만 노출
      base-path: /management # 경로도 바꿔서 숨김

  endpoint:
    health:
      show-details: always # 개발 환경에서는 always, 운영에서는 when-authorized(허가된 사람만 요청 가능하도록)
  server:
    port: 9090 # Actuator 전용 포트 (방화벽 같은데에서 Actuator는 허용된 ip만 접근이 가능하도록 막음)

springdoc:
  swagger-ui:
    path: /api-docs-ui.html # UI page 경로
    tags-sorter: alpha # 태그 정렬 방식 (알파벳순)
    operations-sorter: method # 메서드 정렬 방식
    display-request-duration: true # 요청과 응답에 소요된 시간 표시
    doc-expansion: list # 문서 펼침 상태 (none, list, full)

  api-docs:
    path: /my-api # Swagger가 우리 API의 정보를 얻어오기 위해서 요청하는 url

sprintlog:
  welcome-message: "SprintLog Boot - 외부 설정 시연(기본)"
  sample-data:
    enabled: true
    count: 4
  file-directory: C:\Users\alswo\Desktop\codeit-13th-develop\sprintlog-boot\files

logging:
  level:
    com.sprintlog: debug  #hibernate가 실제로 완성하는 SQL과 7자리에 채워지는 바인딩 값을 함께 보기 위함
#    org.hibernate.sql: debug
#    org.hibernate.orm.jdbc.bind: trace
